version: '2'
services:
  api:
    image: node:10.15.3-alpine
    container_name: tqd-node
    build: .
    #ports:
      #- 3000:3000
    environment:
     - NODE_ENV=local
     - ES_HOST=elasticsearch
     #- NODE_PORT=3000
     - ELASTIC_URL=http://elasticsearch
    volumes:
      - .:/usr/src/app/quotes
    command: npm run start
    links:
        - elasticsearch
    depends_on:
        - elasticsearch

  elasticsearch:
    container_name: tqd-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    logging:
      driver: none
    #ports:
      #- 9300:9300
      #- 9200:9200

volumes:
  esdata: {}